name: Game

    #工作流的名称

on:
    push:
        branches:
            - master

    # 这个工作流在push到game分支时触发
jobs:
    test:

        name: Test

        runs-on: windows-latest

            # 在windows-latest环境中运行
        steps:

            - uses: actions/checkout@v2

                # 把该仓库checkout到运行环境中



            - uses: actions/setup-java@v2

              with:

                    java-version: "11"

                    distribution: "adopt"

                # 设置java11环境，附带maven



            - run: npm test

                # 执行`mvn test`命令


