name: Test

    #工作流的名称

on:
    push

    # 这个工作流在push到game分支时触发
jobs:
    test:

        name: Test

        runs-on: ubuntu-latest

            # 在windows-latest环境中运行
        steps:

            - uses: actions/checkout@v2

                # 把该仓库checkout到运行环境中



            - uses: actions/setup-java@v2

              with:

                    java-version: "11"

                    distribution: "adopt"

                # 设置java11环境，附带maven
            - name: MongoDB in GitHub Actions
              # You may pin to the exact commit or the version.
              # uses: supercharge/mongodb-github-action@e815fd8a9dfede09fd6e6c144f2c9f4875e933df
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                   # MongoDB version to use (default "latest")
                   mongodb-version: 5.0.9
                   # MongoDB replica set name (no replica set by default)
   
                   # MongoDB port to use (default 27017)
                   mongodb-port: 27017 
                   # MongoDB db to create (default: none)
                   mongodb-db: caveadventure
                   # MongoDB root username (default: none)
                   mongodb-username: root
                   # MongoDB root password (default: none)
                   mongodb-password: 123456

            - name: MySQL Deploy Action
              # You may pin to the exact commit or the version.
              # uses: calxus/mysql-deploy-action@a2c3adfffe4002b02a06c3deb43449d69803c21b
			  uses: calxus/mysql-deploy-action@v1
			  with:
			      DATABASE_HOST: root
			      DATABASE_PORT: 3306
			      DATABASE_USERNAME: root
			      DATABASE_PASSWORD: 123456
				  DATABASE_NAME: caveadventure
    		       
   


            - run: mvn test

                # 执行`mvn test`命令


